import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class AirportService {

    List() {
        return this.airportList;
    }

    GetCode(name: string){
        var regex = /\(.*\)/g
        var matches = name.match(regex)
        return matches.length ? matches[0].substring(1, 4) : '';
    }

    private airportList = [
        'Aberdeen, SD (ABR)',
        'Abilene, TX (ABI)',
        'Akron/Canton, OH (CAK)',
        'Alamogordo, NM (ALM)',
        'Alamosa, CO (ALS)',
        'Albany, NY (ALB)',
        'Albuquerque, NM (ABQ)',
        'Alexandria, LA (AEX)',
        'Allentown, PA (ABE)',
        'Alliance, NE (AIA)',
        'Alpena, MI (APN)',
        'Altoona, PA (AOO)',
        'Amarillo, TX (AMA)',
        'Anchorage, AK (ANC)',
        'Aniak, AK (ANI)',
        'Appleton, WI (ATW)',
        'Arcata, CA (ACV)',
        'Asheville, NC (AVL)',
        'Ashland, KY/Huntington, WV (HTS)',
        'Aspen, CO (ASE)',
        'Athens, GA (AHN)',
        'Atlanta, GA (ATL)',
        'Atlantic City, NJ (AIY)',
        'Augusta, GA (AGS)',
        'Augusta, ME (AUG)',
        'Austin, TX (AUS)',
        'Bakersfield, CA (BFL)',
        'Baltimore, MD (BWI)',
        'Bangor, ME (BGR)',
        'Barrow, AK (BRW)',
        'Baton Rouge, LA (BTR)',
        'Bay City, MI (MBS)',
        'Beaumont/Port Arthur, TX (BPT)',
        'Beckley, WV (BKW)',
        'Bedford, MA (BED)',
        'Bellingham, WA (BLI)',
        'Bemidji, MN (BJI)',
        'Benton Harbor, MI (BEH)',
        'Bethel, AK (BET)',
        'Bethlehem, PA (ABE)',
        'Billings, MT (BIL)',
        'Biloxi/Gulfport, MS (GPT)',
        'Binghamton, NY (BGM)',
        'Birmingham, AL (BHM)',
        'Bismarck, ND (BIS)',
        'Bloomington, IL (BMI)',
        'Bluefield, WV (BLF)',
        'Boise, ID (BOI)',
        'Boston, MA (BOS)',
        'Boulder, CO - Hiltons Har H (WHH)',
        'Boulder, CO - Municipal Airport (WBU)',
        'Bozeman, MT (BZN)',
        'Bradford, PA (BFD)',
        'Brainerd, MN (BRD)',
        'Bristol, VA (TRI)',
        'Brookings, SD (BKX)',
        'Brownsville, TX (BRO)',
        'Brunswick, GA (BQK)',
        'Buffalo, NY (BUF)',
        'Bullhead City/Laughlin, AZ (IFP)',
        'Burbank, CA (BUR)',
        'Burlington, IA (BRL)',
        'Burlington, VT (BTV)',
        'Butte, MT (BTM)',
        'Canton/Akron, OH (CAK)',
        'Carlsbad, CA (CLD)',
        'Carmel, CA (MRY)',
        'Casper, WY (CPR)',
        'Cedar City, UT (CDC)',
        'Cedar Rapids, IA (CID)',
        'Chadron, NE (CDR)',
        'Champaign/Urbana, IL (CMI)',
        'Charleston, SC (CHS)',
        'Charleston, WV (CRW)',
        'Charlotte, NC (CLT)',
        'Charlottesville, VA (CHO)',
        'Chattanooga, TN (CHA)',
        'Cheyenne, WY (CYS)',
        'Chicago, IL - Meigs (CGX)',
        'Chicago, IL - All airports (CHI)',
        'Chicago, IL - Midway (MDW)',
        'Chicago, IL - O\'Hare (ORD)',
        'Chico, CA (CIC)',
        'Chignik, AK - Fisheries (KCG)',
        'Chignik, AK - Lagoon (KCL)',
        'Chisholm/Hibbing, MN (HIB)',
        'Cincinnati, OH (CVG)',
        'Clarksburg, WV (CKB)',
        'Clearwater/St Petersburg, FL (PIE)',
        'Cleveland, OH (CLE)',
        'Clovis, NM (CVN)',
        'Cody/Yellowstone, WY (COD)',
        'College Station, TX (CLL)',
        'Colorado Springs, CO (COS)',
        'Columbia, MO (COU)',
        'Columbia, SC (CAE)',
        'Columbus, GA (CSG)',
        'Columbus, MS (GTR)',
        'Columbus, OH (CMH)',
        'Cordova, AK (CDV)',
        'Corpus Christi, TX (CRP)',
        'Cortez, CO (CEZ)',
        'Crescent City, CA (CEC)',
        'Cumberland, MD (CBE)',
        'Dallas/Fort Worth, TX (DFW)',
        'Dayton, OH (DAY)',
        'Daytona Beach, FL (DAB)',
        'Decatur, IL (DEC)',
        'Denver, CO - International (DEN)',
        'Des Moines, IA (DSM)',
        'Detroit, MI - All airports (DTT)',
        'Detroit, MI - Metro/Wayne County (DTW)',
        'Devil\'s Lake, ND (DVL)',
        'Dickinson, ND (DIK)',
        'Dillingham, AK (DLG)',
        'Dodge City, KS (DDC)',
        'Dothan, AL (DHN)',
        'Dubois, PA (DUJ)',
        'Dubuque, IA (DBQ)',
        'Duluth, MN (DLH)',
        'Durango, CO (DRO)',
        'Durham, NC (RDU)',
        'Durham/Raleigh, NC (RDU)',
        'Dutch Harbor, AK (DUT)',
        'Easton, PA (ABE)',
        'Eau Claire, WI (EAU)',
        'El Centro, CA (IPL)',
        'El Paso, TX (ELP)',
        'Elko, NV (EKO)',
        'Elmira, NY (ELM)',
        'Ely, MN (LYU)',
        'Endicott, NY (BGM)',
        'Enid, OK (WDG)',
        'Erie, PA (ERI)',
        'Escanaba, MI (ESC)',
        'Eugene, OR (EUG)',
        'Eureka/Arcata, CA (ACV)',
        'Evansville, IN (EVV)',
        'Fairbanks, AK (FAI)',
        'Fargo, ND (FAR)',
        'Fayetteville, AR - Municipal/Drake (FYV)',
        'Fayetteville, AR - Northwest Arkansas Regional (XNA)',
        'Fayetteville, NC (FAY)',
        'Flagstaff, AZ (FLG)',
        'Flint, MI (FNT)',
        'Florence, SC (FLO)',
        'Florence/Muscle Shoals/Sheffield, AL (MSL)',
        'Fort Collins/Loveland, CO - Municipal Airport (FNL)',
        'Fort Dodge, IA (FOD)',
        'Fort Lauderdale, FL (FLL)',
        'Fort Myers, FL (RSW)',
        'Fort Smith, AR (FSM)',
        'Fort Walton Beach, FL (VPS)',
        'Fort Wayne, IN (FWA)',
        'Fort Worth/Dallas, TX (DFW)',
        'Franklin, PA (FKL)',
        'Fresno, CA (FAT)',
        'Gainesville, FL (GNV)',
        'Garden City, KS (GCK)',
        'Gary, IN (GYY)',
        'Gillette, WY (GCC)',
        'Gladewater/Kilgore, TX (GGG)',
        'Grand Canyon, AZ - National Park (GCN)',
        'Grand Forks, ND (GFK)',
        'Grand Island, NE (GRI)',
        'Grand Junction, CO (GJT)',
        'Grand Rapids, MI (GRR)',
        'Grand Rapids, MN (GPZ)',
        'Great Falls, MT (GTF)',
        'Green Bay, WI (GRB)',
        'Greensboro, NC (GSO)',
        'Greenville, MS (GLH)',
        'Greenville, NC (PGV)',
        'Greenville/Spartanburg, SC (GSP)',
        'Groton/New London, CT (GON)',
        'Gulfport, MS (GPT)',
        'Gunnison, CO (GUC)',
        'Gustavus, AK (GST)',
        'Hagerstown, MD (HGR)',
        'Hailey, ID (SUN)',
        'Hampton, VA (PHF)',
        'Hancock, MI (CMX)',
        'Hanover, NH (LEB)',
        'Harlingen, TX (HRL)',
        'Harrisburg, PA (MDT)',
        'Hartford, CT (BDL)',
        'Hayden, CO (HDN)',
        'Hays, KS (HYS)',
        'Helena, MT (HLN)',
        'Hendersonville, NC (AVL)',
        'Hibbing/Chisholm, MN (HIB)',
        'Hickory, NC (HKY)',
        'High Point, NC (GSO)',
        'Hilo, HI - Island of Hawaii (ITO)',
        'Hilton Head, SC (HHH)',
        'Honolulu, HI - Island of Oahu (HNL)',
        'Hoolehua, HI - Island of Molokai (MKK)',
        'Houston, TX - All airports (HOU)',
        'Houston, TX - Hobby (HOU)',
        'Houston, TX - Intercontinental (IAH)',
        'Huntington, WV/Ashland, KY (HTS)',
        'Huntsville, AL (HSV)',
        'Huron, SD (HON)',
        'Hyannis, MA (HYA)',
        'Idaho Falls, ID (IDA)',
        'Imperial, CA (IPL)',
        'Indianapolis, IN (IND)',
        'International Falls, MN (INL)',
        'Inyokern, CA (IYK)',
        'Iron Mountain, MI (IMT)',
        'Ironwood, MI (IWD)',
        'Islip, NY (ISP)',
        'Ithaca, NY (ITH)',
        'Jackson Hole, WY (JAC)',
        'Jackson, MS (JAN)',
        'Jackson, TN (MKL)',
        'Jacksonville, FL (JAX)',
        'Jacksonville, NC (OAJ)',
        'Jamestown, ND (JMS)',
        'Jamestown, NY (JHW)',
        'Johnson City, NY (BGM)',
        'Johnson City, TN (TRI)',
        'Johnstown, PA (JST)',
        'Joplin, MO (JLN)',
        'Juneau, AK (JNU)',
        'Kahului, HI - Island of Maui, (OGG)',
        'Kalamazoo, MI (AZO)',
        'Kansas City, MO (MCI)',
        'Kapalua, HI - Island of Maui, (JHM)',
        'Kauai Island/Lihue, HI (LIH)',
        'Kearney, NE (EAR)',
        'Ketchikan, AK (KTN)',
        'Key West, FL (EYW)',
        'Kiana, AK (IAN)',
        'Kilgore/Gladewater, TX (GGG)',
        'Killeen, TX (ILE)',
        'King Salmon, AK (AKN)',
        'Kingsport, TN (TRI)',
        'Klamath Falls, OR (LMT)',
        'Knoxville, TN (TYS)',
        'Kodiak, AK (ADQ)',
        'Kona, HI - Island of Hawaii (KOA)',
        'Kotzebue, AK (OTZ)',
        'La Crosse, WI (LSE)',
        'Lafayette, IN (LAF)',
        'Lafayette, LA (LFT)',
        'Lake Charles, LA (LCH)',
        'Lake Havasu City, AZ (HII)',
        'Lanai City, HI - Island of Lanai (LNY)',
        'Lancaster, PA (LNS)',
        'Lansing, MI (LAN)',
        'Laramie, WY (LAR)',
        'Laredo, TX (LRD)',
        'Las Vegas, NV (LAS)',
        'Latrobe, PA (LBE)',
        'Laurel, MS (PIB)',
        'Lawton, OK (LAW)',
        'Lebanon, NH (LEB)',
        'Lewisburg, WV (LWB)',
        'Lewiston, ID (LWS)',
        'Lexington, KY (LEX)',
        'Liberal, KS (LBL)',
        'Lihue, HI - Island of Kaui (LIH)',
        'Lincoln, NE (LNK)',
        'Little Rock, AR (LIT)',
        'Long Beach, CA (LGB)',
        'Longview, TX (GGG)',
        'Los Angeles, CA (LAX)',
        'Louisville, KY (SDF)',
        'Loveland/Fort Collins, CO - Municipal Airport (FNL)',
        'Lubbock, TX (LBB)',
        'Macon, GA (MCN)',
        'Madison, WI (MSN)',
        'Manchester, NH (MHT)',
        'Manhattan, KS (MHK)',
        'Manistee, MI (MBL)',
        'Mankato, MN (MKT)',
        'Marietta, OH/Parkersburg, WV (PKB)',
        'Marquette, MI (MQT)',
        'Martha\'s Vineyard, MA (MVY)',
        'Martinsburg, PA (AOO)',
        'Mason City, IA (MCW)',
        'Massena, NY (MSS)',
        'Maui, HI (OGG)',
        'Mcallen, TX (MFE)',
        'Medford, OR (MFR)',
        'Melbourne, FL (MLB)',
        'Memphis, TN (MEM)',
        'Merced, CA (MCE)',
        'Meridian, MS (MEI)',
        'Miami, FL - International (MIA)',
        'Midland, MI (MBS)',
        'Midland/Odessa, TX (MAF)',
        'Milwaukee, WI (MKE)',
        'Minneapolis, MN (MSP)',
        'Minot, ND (MOT)',
        'Mission, TX (MFE)',
        'Missoula, MT (MSO)',
        'Mobile, AL (MOB)',
        'Modesto, CA (MOD)',
        'Moline, IL (MLI)',
        'Monroe, LA (MLU)',
        'Monterey, CA (MRY)',
        'Montgomery, AL (MGM)',
        'Montrose, CO (MTJ)',
        'Morgantown, WV (MGW)',
        'Moses Lake, WA (MWH)',
        'Muscle Shoals, AL (MSL)',
        'Muskegon, MI (MKG)',
        'Myrtle Beach, SC (MYR)',
        'Nantucket, MA (ACK)',
        'Naples, FL (APF)',
        'Nashville, TN (BNA)',
        'New Haven, CT (HVN)',
        'New London/Groton (GON)',
        'New Orleans, LA (MSY)',
        'New York, NY - All airports (NYC)',
        'New York, NY - Kennedy (JFK)',
        'New York, NY - La Guardia (LGA)',
        'Newark, NJ (EWR)',
        'Newburgh/Stewart Field, NY (SWF)',
        'Newport News, VA (PHF)',
        'Nome, AK (OME)',
        'Norfolk, NE (OFK)',
        'Norfolk, VA (ORF)',
        'North Bend, OR (OTH)',
        'North Platte, NE (LBF)',
        'Oakland, CA (OAK)',
        'Odessa/Midland, TX (MAF)',
        'Ogdensburg, NY (OGS)',
        'Oklahoma City, OK (OKC)',
        'Omaha, NE (OMA)',
        'Ontario, CA (ONT)',
        'Orange County, CA (SNA)',
        'Orlando, FL - Herndon (ORL)',
        'Orlando, FL - International (MCO)',
        'Oshkosh, WI (OSH)',
        'Ottumwa, IA (OTM)',
        'Owensboro, KY (OWB)',
        'Oxnard/Ventura, CA (OXR)',
        'Paducah, KY (PAH)',
        'Page, AZ (PGA)',
        'Palm Springs, CA (PSP)',
        'Panama City, FL (PFN)',
        'Parkersburg, WV/Marietta, OH (PKB)',
        'Pasco, WA (PSC)',
        'Pellston, MI (PLN)',
        'Pendleton, OR (PDT)',
        'Pensacola, FL (PNS)',
        'Peoria, IL (PIA)',
        'Petersburg, AK (PSG)',
        'Philadelphia, PA - International (PHL)',
        'Philadelphia, PA - Trenton/Mercer NJ (TTN)',
        'Phoenix, AZ (PHX)',
        'Pierre, SD (PIR)',
        'Pilot Point, AK - Ugashnik Bay (UGB)',
        'Pilot Point, AK (PIP)',
        'Pittsburgh, PA (PIT)',
        'Plattsburgh, NY (PLB)',
        'Pocatello, ID (PIH)',
        'Ponce, Puerto Rico (PSE)',
        'Port Angeles, WA (CLM)',
        'Port Arthur/Beaumont, TX (BPT)',
        'Portland, ME (PWM)',
        'Portland, OR (PDX)',
        'Portsmouth, NH (PSM)',
        'Poughkeepsie, NY (POU)',
        'Prescott, AZ (PRC)',
        'Presque Isle, ME (PQI)',
        'Princeton, WV (BLF)',
        'Providence, RI (PVD)',
        'Prudhoe Bay/Deadhorse, AK (SCC)',
        'Pueblo, CO (PUB)',
        'Pullman, WA (PUW)',
        'Quincy, IL (UIN)',
        'Raleigh/Durham, NC (RDU)',
        'Rapid City, SD (RAP)',
        'Reading, PA (RDG)',
        'Redding, CA (RDD)',
        'Redmond, OR (RDM)',
        'Reno, NV (RNO)',
        'Rhinelander, WI, (RHI)',
        'Richmond, VA (RIC)',
        'Riverton, WY (RIW)',
        'Roanoke, VA (ROA)',
        'Rochester, MN (RST)',
        'Rochester, NY (ROC)',
        'Rock Springs, WY (RKS)',
        'Sacramento, CA (SMF)',
        'Saginaw, MI (MBS)',
        'Saint Cloud, MN (STC)',
        'Saint George, UT (SGU)',
        'Saint Louis, MO (STL)',
        'Saint Mary\'s, AK (KSM)',
        'Salem, OR (SLE)',
        'Salina, KS (SLN)',
        'Salisbury-Ocean City, MD (SBY)',
        'Salt Lake City, UT (SLC)',
        'San Angelo, TX (SJT)',
        'San Antonio, TX (SAT)',
        'San Diego, CA (SAN)',
        'San Francisco, CA (SFO)',
        'San Jose, CA (SJC)',
        'San Juan, Puerto Rico (SJU)',
        'San Luis Obispo, CA (SBP)',
        'Santa Ana, CA (SNA)',
        'Santa Barbara, CA (SBA)',
        'Santa Fe, NM (SAF)',
        'Santa Maria, CA (SMX)',
        'Santa Rosa, CA (STS)',
        'Saranac Lake, NY (SLK)',
        'Sarasota, FL (SRQ)',
        'Sault Ste Marie, MI, (CIU)',
        'Savannah, GA (SAV)',
        'Scottsbluff, NE (BFF)',
        'Scottsdale, AZ (SDL)',
        'Scranton, PA (AVP)',
        'Seattle, WA - Lake Union SPB (LKE)',
        'Seattle, WA - Seattle/Tacoma International (SEA)',
        'Sheffield/Florence/Muscle Shoals, AL (MSL)',
        'Sheridan, WY (SHR)',
        'Shreveport, LA (SHV)',
        'Sioux City, IA (SUX)',
        'Sioux Falls, SD (FSD)',
        'Sitka, AK (SIT)',
        'South Bend, IN (SBN)',
        'Southern Pines, NC (SOP)',
        'Spartanburg/Greenville, SC (GSP)',
        'Spokane, WA (GEG)',
        'Springfield, IL (SPI)',
        'Springfield, MO (SGF)',
        'St Petersburg/Clearwater, FL (PIE)',
        'State College/University Park, PA (SCE)',
        'Staunton, VA (SHD)',
        'Steamboat Springs, CO (SBS)',
        'Stevens Point/Wausau, WI (CWA)',
        'Stewart Field/Newburgh, NY (SWF)',
        'Stockton, CA (SCK)',
        'Sun Valley, ID (SUN)',
        'Syracuse, NY (SYR)',
        'Tallahassee, FL (TLH)',
        'Tampa, FL (TPA)',
        'Telluride, CO (TEX)',
        'Terre Haute, IN (HUF)',
        'Texarkana, AR (TXK)',
        'Thief River Falls, MN (TVF)',
        'Toledo, OH (TOL)',
        'Topeka, KS (FOE)',
        'Traverse City, MI (TVC)',
        'Trenton/Mercer, NJ (TTN)',
        'Tucson, AZ (TUS)',
        'Tulsa, OK (TUL)',
        'Tupelo, MS (TUP)',
        'Tuscaloosa, AL (TCL)',
        'Twin Falls, ID (TWF)',
        'Tyler, TX (TYR)',
        'Urbana/Champaign, IL (CMI)',
        'Utica, NY (UCA)',
        'Vail, CO - Eagle County Airport (EGE)',
        'Valdosta, GA (VLD)',
        'Valparaiso, FL (VPS)',
        'Ventura/Oxnard, CA (OXR)',
        'Vernal, UT (VEL)',
        'Victoria, TX (VCT)',
        'Visalia, CA (VIS)',
        'Waco, TX (ACT)',
        'Walla Walla, WA (ALW)',
        'Washington DC - All airports (WAS)',
        'Washington DC - Dulles (IAD)',
        'Washington DC - National (DCA)',
        'Waterloo, IA (ALO)',
        'Watertown, NY (ART)',
        'Watertown, SD (ATY)',
        'Wausau/Stevens Point, WI (CWA)',
        'Wenatchee, WA (EAT)',
        'West Palm Beach, FL (PBI)',
        'West Yellowstone, MT (WYS)',
        'Westchester County, NY (HPN)',
        'White River, VT (LEB)',
        'Wichita Falls, TX (SPS)',
        'Wichita, KS (ICT)',
        'Wilkes Barre, PA (AVP)',
        'Williamsburg, VA (PHF)',
        'Williamsport, PA (IPT)',
        'Williston, ND (ISN)',
        'Wilmington, NC (ILM)',
        'Windsor Locks, CT (BDL)',
        'Worcester, MA (ORH)',
        'Worland, WY (WRL)',
        'Wrangell, AK (WRG)',
        'Yakima, WA (YKM)',
        'Yakutat, AK (YAK)',
        'Yellowstone/Cody, WY (COD)',
        'Youngstown, OH (YNG)',
        'Yuma, AZ (YUM)',
        'Aalborg, Denmark (AAL)',
        'Aalesund, Norway (AES)',
        'Aarhus, Denmark - Tirstrup (AAR)',
        'Aberdeen, United Kingdom (ABZ)',
        'Abidjan, Cote d\'Ivoire (ABJ)',
        'Abu Dhabi, United Arab Emirates (AUH)',
        'Abu Simbel, Egypt (ABS)',
        'Abuja, Nigeria (ABV)',
        'Acapulco, Mexico (ACA)',
        'Accra, Ghana (ACC)',
        'Adana, Turkey (ADA)',
        'Addis Ababa, Ethopia (ADD)',
        'Adelaide, Australia (ADL)',
        'Aden, Yemen (ADE)',
        'Agadir, Morocco (AGA)',
        'Aguadilla, Puerto Rico (BQN)',
        'Aguascalientes, Mexico (AGU)',
        'Ahmedabad, India (AMD)',
        'Ahwaz, Iran (AWZ)',
        'Ajaccio, France (AJA)',
        'Akita, Japan (AXT)',
        'Al Ain, United Arab Emirates (AAN)',
        'Al Hoceima, Morocco (AHU)',
        'Albury, Australia (ABX)',
        'Aleppo, Syrian Arab Republic (ALP)',
        'Alexandria, Egypt (ALY)',
        'Alexandroupolis, Greece (AXD)',
        'Al-Fujairah, United Arab Emirates (FJR)',
        'Alghero, Italy (AHO)',
        'Algiers, Algeria (ALG)',
        'Alicante, Spain (ALC)',
        'Alice Springs, Australia (ASP)',
        'Almeria, Spain (LEI)',
        'Alorsetar, Malaysia (AOR)',
        'Alta, Norway (ALF)',
        'Amami O Shima, Japan (ASJ)',
        'Ambon, Indonesia (AMQ)',
        'Amman, Jordan - Queen Alia International (AMM)',
        'Amman, Jordan - Civil/Marka Airport (ADJ)',
        'Amritsar, India (ATQ)',
        'Amsterdam, Netherlands (AMS)',
        'Anapa, Russia (AAQ)',
        'Ancona, Italy (AOI)',
        'Angers, France - Marce (ANE)',
        'Anguilla, Anguilla (AXA)',
        'Ankara, Turkey - Esenboga (ESB)',
        'Ankara, Turkey - Etimesqut (ANK)',
        'Annecy, France (NCY)',
        'Antalya, Turkey (AYT)',
        'Antaninvarivo, Madgascar (TNR)',
        'Antigua, Antigua and Barbuda (ANU)',
        'Antofagasta, Chile (ANF)',
        'Antwerp, Belgium - Deurne Airport (ANR)',
        'Aomori, Japan (AOJ)',
        'Apia, Western Samoa (APW)',
        'Apia, Western Samoa (FGI)',
        'Aqaba, Jordan (AQJ)',
        'Araca, Brazil (AJU)',
        'Arequipa, Peru (AQP)',
        'Argelholm/Helsingborg, Sweden (AGH)',
        'Arica, Chile (ARI)',
        'Arkangelsk, Russia (ARH)',
        'Armenia, Colombia (AXM)',
        'Aruba, Aruba (AUA)',
        'Asahikawa, Japan (AKJ)',
        'Ashgabat, Turkmenistan (ASB)',
        'Asmara, Eritrea (ASM)',
        'Asturias, Spain and Canary Islands (OVD)',
        'Asuncion, Paraguay (ASU)',
        'Aswan, Egypt (ASW)',
        'Athens, Greece (ATH)',
        'Auckland, New Zealand (AKL)',
        'Augsburg/Munich, Germany (AGB)',
        'Aurangabad, India (IXU)',
        'Aurillac, France (AUR)',
        'Avignon, France (AVN)',
        'Ayers Rock, Australia (AYQ)',
        'Bacolod, Philippines (BCD)',
        'Bagdogra, India (IXB)',
        'Bahia Blanca, Argentina (BHI)',
        'Bahrain, Bahrain (BAH)',
        'Baku, Azerbaijan (BAK)',
        'Balikpapan, Indonesia (BPN)',
        'Balmaceda, Chile (BBA)',
        'Bamako, Mali (BKO)',
        'Banda Aceh, Indonesia (BTJ)',
        'Bandar Seri Begawan, Brunei (BWN)',
        'Bandung, Indonesia (BDO)',
        'Bangalore, India (BLR)',
        'Bangkok, Thailand (BKK)',
        'Banja Luka, Bosnia Herzegovina (BNX)',
        'Banjarmasin, Indonesia (BDJ)',
        'Banjul, Gambia (BJL)',
        'Banqui, Central African Republic (BGF)',
        'Barcelona, Spain (BCN)',
        'Barcelona, Venezuela (BLA)',
        'Bardufoss, Norway (BDU)',
        'Bari, Italy (BRI)',
        'Barra, United Kingdom (BRR)',
        'Barran Cabermeja, Colombia (EJA)',
        'Barranquilla, Colombia (BAQ)',
        'Basel, Switzerland (BSL)',
        'Bastia, France (BIA)',
        'Batam, Indonesia (BTH)',
        'Batman, Turkey (BAL)',
        'Bayreuth, Germany (BYU)',
        'Beef Island, British Virgin Islands (EIS)',
        'Beihai, China (BHY)',
        'Beijing, China (PEK)',
        'Beira, Mozambique (BEW)',
        'Beirut, Lebanon (BEY)',
        'Belem, Brazil (BEL)',
        'Belfast, Northern Ireland, United Kingdom (BFS)',
        'Belfast, United Kingdom (BHD)',
        'Belgrade, Serbia and Montenegro - Beograd (BEG)',
        'Belize City, Belize - International (BZE)',
        'Belize City, Belize - Municipal (TZA)',
        'Belo Horizonte, Brazil - Tancredo Neves Intl. (CNF)',
        'Belo Horizonte, Brazil - Pampulha (PLU)',
        'Benbecula, United Kingdom (BEB)',
        'Benghazi, Libya (BEN)',
        'Bengkulu, Indonesia (BKS)',
        'Bergen, Norway (BGO)',
        'Berlin, Germany - All airports (BER)',
        'Berlin, Germany - Tegel (TXL)',
        'Berlin, Germany - Tempelhof (THF)',
        'Berlin, Germany - Schoenefeld (SXF)',
        'Bermuda, Bermuda (BDA)',
        'Berne, Switzerland - Belp Airport (BRN)',
        'Berne, Switzerland - Rail service (ZDJ)',
        'Beziers, France (BZR)',
        'Bhavnagar, India (BHU)',
        'Bhopal, India (BHO)',
        'Bhubaneswar, India (BBI)',
        'Bhuj, India (BHJ)',
        'Biak, Indonesia (BIK)',
        'Biarritz, France (BIQ)',
        'Bikini Atoll, Marshall Islands (BII)',
        'Bilbao, Spain (BIO)',
        'Billund, Denmark (BLL)',
        'Bimini, Bahamas (BIM)',
        'Bintulu, Malaysia (BTU)',
        'Birmingham, United Kingdom (BHX)',
        'Bishkek, Kyrgyzstan (FRU)',
        'Bissau, Guinea-Bissau (OXB)',
        'Blantyre, Malawi (BLZ)',
        'Blenheim, New Zealand (BHE)',
        'Blo Horizonte, Brazil (CNF)',
        'Bloemfontein, South Africa (BFN)',
        'Boavista, Brazil (BVB)',
        'Bodo, Norway (BOO)',
        'Bodrum, Turkey (BJV)',
        'Bogota, Colombia (BOG)',
        'Bombay, India (BOM)',
        'Bonaire, Netherlands Antilles (BON)',
        'Bonn, Germany (BNJ)',
        'Bora Bora, French Polynesia (BOB)',
        'Bordeaux, France (BOD)',
        'Borg El Arab, Egypt (HBE)',
        'Borlange, Sweden (BLE)',
        'Bornholm, Denmark (RNN)',
        'Bourgas, Bulgaria (BOJ)',
        'Brasilia, DF, Brazil (BSB)',
        'Bratislava, Slovakia (BTS)',
        'Brazzaville, Congo (BZV)',
        'Bremen, Germany (BRE)',
        'Brest, France (BES)',
        'Bridgetown, Barbados (BGI)',
        'Brindisi, Italy (BDS)',
        'Brisbane, Queensland, Australia (BNE)',
        'Bristol, United Kingdom (BRS)',
        'Brive-La-Gaillarde, France - Laroche(BVE)',
        'Brno, Czech Republic - Turany (BRQ)',
        'Brno, Czech Republic - Bus service (ZDN)',
        'Broome, Australia (BME)',
        'Brussels, Belgium - National (BRU)',
        'Brussels, Belguim - Charleroi (CRL)',
        'Bucaramanga, Colombia (BGA)',
        'Bucharest, Romania - Baneasa (BBU)',
        'Bucharest, Romania - Otopeni International (OTP)',
        'Budapest, Hungary (BUD)',
        'Buenos Aires, Argentina - Jorge Newbery (AEP)',
        'Buenos Aires, Argentina - Ministro Pistarini (EZE)',
        'Bujumbura, Burundi (BJM)',
        'Bulawayo, Zimbabwe (BUQ)',
        'Busan, South Korea - Gimhae (PUS)',
        'Cabo San Lucas, \'Los Cabos\', Mexico (SJD)',
        'Caen, France (CFR)',
        'Cagayan De Oro, Philippines - Lumbia (CGY)',
        'Cagliari, Italy (CAG)',
        'Cairns, Australia (CNS)',
        'Cairo, Egypt (CAI)',
        'Calama, Chile (CJC)',
        'Calcutta, India (CCU)',
        'Cali, Colombia (CLO)',
        'Calvi, France (CLY)',
        'Camodoro, Argentina (CRD)',
        'Campbeltown, United Kingdom (CAL)',
        'Campeche, Mexico (CPE)',
        'Campo Grande, Brazil (CGR)',
        'Canaima, Venezuela (CAS)',
        'Canberra, Australia (CBR)',
        'Cancun, Mexico (CUN)',
        'Cannes, France - Mandelieu (CEQ)',
        'Cape Town, South Africa (CPT)',
        'Caracas, Venezuela (CCS)',
        'Cardiff, United Kingdom (CWL)',
        'Cartagena, Colombia (CTG)',
        'Casablanca, Morocco - Anfa (CAS)',
        'Casablanca, Morocco - Mohamed V (CMN)',
        'Catamarca, Argentina (CTC)',
        'Catania, Italy (CTA)',
        'Cayenne, French Guiana (CAY)',
        'Cayman Brac Is, Cambodia (CYB)',
        'Cebu, Philippines - Matan International (CEB)',
        'Chah-Bahar, Iran (ZBR)',
        'Chandigarh, India (IXC)',
        'Changchun, China (CGQ)',
        'Chania, Greece (CHQ)',
        'Chennai, India (MAA)',
        'Cheongju, South Korea (CJJ)',
        'Chergdu, China (CTU)',
        'Chetumal, Mexico (CTM)',
        'Chiang Mai, Thailand (CNX)',
        'Chiang Rai, Thailand (CEI)',
        'Chicayo, Peru (CIX)',
        'Chihuahua, Mexico (CUU)',
        'Chillan, Chile (YAI)',
        'Chisinau, Republic of Moldova (KIV)',
        'Chittagong, Bangladesh (CGP)',
        'Chongqing, China (CKG)',
        'Christchurch, New Zealand (CHC)',
        'Ciego De Avila, Cuba (AVI)',
        'Ciudad Del Carmen, Mexico (CME)',
        'Ciudad Juarez, Mexico (CJS)',
        'Ciudad Obregon, Mexico (CEN)',
        'Ciudad Victoria, Mexico (CVM)',
        'Clermont-ferrand, France (CFE)',
        'Cluj, Romania (CLJ)',
        'Cochabamba, Bolivia (CBB)',
        'Cochin, India (COK)',
        'Coimbatore, India (CJB)',
        'Colima, Mexico (CLQ)',
        'Cologne, Germany - Rail service (QKL)',
        'Cologne, Germany - Cologne/Bonn (CGN)',
        'Colombo, Sri Lanka (CMB)',
        'Conakry, Guinea (CKY)',
        'Concepcion, Chile (CCP)',
        'Constantine, Algeria (CZL)',
        'Copenhagen, Denmark (CPH)',
        'Copiapo, Chile (CPO)',
        'Cordoba, Argentina (COR)',
        'Cork, Ireland (ORK)',
        'Corrientes, Argentina (CNQ)',
        'Corumba, Brazil (CMG)',
        'Cox\'s Bazar, Bangladesh (CXB)',
        'Cozumel, Mexico (CZM)',
        'Crotone, Italy (CRV)',
        'Cruzeiro Do Sul, Brazil (CZS)',
        'Cucata, Colombia (CUC)',
        'Cuenca, Ecuador (CUE)',
        'Cuiaba, Brazil (CGB)',
        'Culiacan, Mexico (CUL)',
        'Curacao, Netherlands Antilles (CUR)',
        'Curitiba, Brazil (CWB)',
        'Cuzco, Peru (CUZ)',
        'Da Nang, Viet Nam (DAD)',
        'Daegu, South Korea (TAE)',
        'Dakar, Senegal (DKR)',
        'Dalaman, Turkey (DLM)',
        'Dalian, China (DLC)',
        'Damascus, Syrian Arab Republic (DAM)',
        'Dammam, Saudi Arabia (DMM)',
        'Dar Es Salaam, Tanzania (DAR)',
        'Darwin, Northern Territory, Australia (DRW)',
        'Davao, Philipines - Mati (DVO)',
        'Dayang, China (DYG)',
        'Delhi, India (DEL)',
        'Denizli, Turkey (DNZ)',
        'Denpasar Bali, Indonesia (DPS)',
        'Dhaka, Bangledesh - Zia International (DAC)',
        'Dibrugarn, India (DIB)',
        'Dijon, France (DIJ)',
        'Dire Dawa, Ethiopia (DIR)',
        'Div, India (DIU)',
        'Diyarbakir, Turkey (DIY)',
        'Djerba, Tunisia (DJE)',
        'Djibouti, Djibouti (JIB)',
        'Dnepropetrovsk, Ukraine (DNK)',
        'Doha, Qatar (DOH)',
        'Dominica, Dominica - Cane Field (DCF)',
        'Dominica, Dominica - Melville Hall (DOM)',
        'Donetsk, Ukraine (DOK)',
        'Dortmund, Germany (DTM)',
        'Dovala, Cameroon (DLA)',
        'Dresden, Germany (DRS)',
        'Dubai, United Arab Emirates (DXB)',
        'Dublin, Ireland (DUB)',
        'Dubrovnik, Croatia (DBV)',
        'Dumaguete, Philippines (DGT)',
        'Dunedin, New Zealand (DUD)',
        'Durango, Mexico (DGO)',
        'Durban, South Africa (DUR)',
        'Dusseldorf, Germany - International (DUS)',
        'Dusseldorf, Germany - Moenchen-Gl. (MGL)',
        'Dusseldorf, Germany - Rail service (QDU)',
        'East London, South Africa (ELS)',
        'Edinburgh, United Kingdom (EDI)',
        'Eindhoven, Netherlands (EIN)',
        'Ekaterinburg, Russia (SVX)',
        'El Salvador, Chile (ESR)',
        'Elat, Italy (ETH)',
        'Elazig, Turkey (EZS)',
        'Eldoret, Kenya (EDL)',
        'Eleuthera Island, Bahamas (ELH)',
        'Entebbe, Uganda (EBB)',
        'Epinal, France (EPL)',
        'Ercan, Cyprus (ECN)',
        'Erfurt, Germany (ERF)',
        'Erzincan, Turkey (ERC)',
        'Erzurum, Turkey (ERZ)',
        'Faro, Portugal (FAO)',
        'Faroe Islands, Faroe Islands (FAE)',
        'Fez, Morocco (FEZ)',
        'Florence, Italy - Gal Galilei (PSA)',
        'Florence, Italy - Peretola (FLR)',
        'Flores, Guatemala (FRS)',
        'Florianopolis, Brazil (FLN)',
        'Formosa, Argentina (FMA)',
        'Fort De France, Martinique (FDF)',
        'Fortaleza, Brazil (FOR)',
        'Francistown, Botswana (FRW)',
        'Frankfurt, Germany - International (FRA)',
        'Freeport, Bahamas (FPO)',
        'Freetown, Sierra Leone - Lungi Intl (FNA)',
        'Friedrichshafer, Germany (FDH)',
        'Fuerteventura, Spain (FUE)',
        'Fukuoka, Japan (FUK)',
        'Funchal, Portugal (FNC)',
        'Fuzhou, China (FOC)',
        'Gaborone, Botswana (GBE)',
        'Galapagos, Ecuador (GPS)',
        'Galway, Ireland (GWY)',
        'Gangneung, South Korea (KAG)',
        'Gawahati, India (GAU)',
        'Gaziatep, Turkey (GZT)',
        'Gdansk, Poland (GDN)',
        'Geneva, Switzerland (GVA)',
        'Genoa, Italy (GOA)',
        'George Town, Bahamas (GGT)',
        'George, South Africa (GRJ)',
        'Georgetown, Guyana (GEO)',
        'Gerona, Spain (GRO)',
        'Gibraltar, Gibraltar (GIB)',
        'Gisborne, New Zealand (GIS)',
        'Glasgow, United Kingdom - Glasgow International (GLA)',
        'Glasgow, United Kingdom - Prestwick (PIK)',
        'Goa, India (GOI)',
        'Goiania, Brazil (GYN)',
        'Gold Coast, QL, Australia (OOL)',
        'Goroka, Papua New Guinea (GKA)',
        'Gothenburg, Sweden - Landvetter (GOT)',
        'Gothenburg, Sweden - Saeve (GSE)',
        'Governors Harbour, Bahamas (GHB)',
        'Gozo, Malta (GZM)',
        'Granada, Spain (GRX)',
        'Grand Cayman, Cayman Islands (GCM)',
        'Graz, Austria (GRZ)',
        'Grenada, Grenada, (GND)',
        'Grenoble, France (GNB)',
        'Guadalajara, Mexico (GDL)',
        'Guam (GUM)',
        'Guanajuato, Mexico (BJX)',
        'Guangzhou, China (CAN)',
        'Guantanamo, Cuba (GAO)',
        'Guatemala City, Guatemala (GUA)',
        'Guayaquil, Ecuador (GYE)',
        'Guaymas, Mexico (GYM)',
        'Guernsey, United Kingdom (GCI)',
        'Guilin, China (KWL)',
        'Gulyang, China (KWE)',
        'Gunsan, South Korea (KUV)',
        'Gwangju, South Korea (KWJ)',
        'Haifa, Israel (HFA)',
        'Haikou, China (HAK)',
        'Halmstad, Sweden (HAD)',
        'Hamburg, Germany - Fuhisbuettel (HAM)',
        'Hamilton, Bermuda (BDA)',
        'Hamilton, New Zealand (HLZ)',
        'Hangzhou, China (HGH)',
        'Hanoi, Viet Nam - Noibai (HAN)',
        'Hanover, Germany (HAJ)',
        'Harare, Zimbabwe (HRE)',
        'Harbin, China (HRB)',
        'Hargeisa, Somolia (HGA)',
        'Harstad-Narvik, Norway (EVE)',
        'Hassi Messaoud, Algeria (HME)',
        'Hat Yai, Thailand (HDY)',
        'Haugesund, Norway (HAU)',
        'Havana, Cuba (HAV)',
        'Hayman Island, Australia (HIS)',
        'Helsinki, Finland (HEL)',
        'Heraklian, Greece (HER)',
        'Hermosillo, Mexico (HMO)',
        'Hiroshima, Japan - International (HIJ)',
        'Ho Chi Minh City, Viet Nam (SGN)',
        'Hobart, Australia (HBA)',
        'Hoedspruit, South Africa (HDS)',
        'Hof, Germany (HOQ)',
        'Hokitika, New Zealand (HKK)',
        'Holguin, Cuba (HOG)',
        'Hong Kong, Hong Kong (HKG)',
        'Horta, Portugal (HOR)',
        'Hualtin, Thailand (HHQ)',
        'Huatulco, Mexico (HUX)',
        'Hultsfred, Sweden (HLF)',
        'Humberside, United Kingdom (HUY)',
        'Hurghada, Egypt (HRG)',
        'Hwange Nat Park, Zimbabwe (HWN)',
        'Hyderabad, India (HYD)',
        'Iasi, Romania (IAS)',
        'Ibague, Colombia (IBE)',
        'Ibiza, Spain (IBZ)',
        'Iguassu Falls, PR, Brazil (IGU)',
        'Iguazu, Argentina (IGR)',
        'Ilheus, Brazil (IOS)',
        'Iloilo, Philippines - Mandurriao (ILO)',
        'Imphal, India (IMF)',
        'Inagua, Bahamas (IGA)',
        'Indore, India (IDR)',
        'Innsbruck, Austria (INN)',
        'Invercargill, New Zealand (IVC)',
        'Inverness, United Kingdom (INV)',
        'Ioannina, Greece (IOA)',
        'Ipoh, Malaysia (IPH)',
        'Iquique, Chile (IQQ)',
        'Iquitos, Peru (IQT)',
        'Isfahan, Iran (IFN)',
        'Islamabad, Pakistan (ISB)',
        'Islay, United Kingdom (ILY)',
        'Istanbul, Turkey (IST)',
        'Ixtapa, Mexico (ZIH)',
        'Izmir, Turkey (ADB)',
        'Izumo, Japan (IZO)',
        'Jaipur, India (JAI)',
        'Jakarta, Indonesia (CGK)',
        'Jalapa, Mexico (JAL)',
        'Jayapura, Indonesia (DJJ)',
        'Jeddah, Saudi Arabia (JED)',
        'Jeju, South Korea - Jeju Airport, metro area (CJU)',
        'Jerez De La Frontere, Spain (XRY)',
        'Jersey, United Kingdom (JER)',
        'Jessore, Bangladesh (JSR)',
        'Jinan, China (TNA)',
        'Jinghong, China (JHG)',
        'Jinju, South Korea - Sancheon (HIN)',
        'Joao Pessoa, Brazil (JPA)',
        'Jodhpur, India (JDH)',
        'Johannesburg, South Africa (JNB)',
        'Johor, Malaysia (JHB)',
        'Joinville, Brazil (JOI)',
        'Jommu, India (IXJ)',
        'Jonkoping, Sweden (JKG)',
        'Jorhat, India (JRH)',
        'Jujuy, Argentina (JUJ)',
        'Juliaca, Peru (JUL)',
        'Jyvaskyla, Finland (JYV)',
        'Kabul, Afghanistan (KBL)',
        'Kaitaia, New Zealand (KAT)',
        'Kaliningrad, Russia (KGD)',
        'Kano, Nigeria (KAN)',
        'Karachi, Pakistan - Quaid-E-Azam International (KHI)',
        'Kariba, Zimbabwe (KAB)',
        'Karpathos, Greece (AOK)',
        'Kasane, Botswana (BBK)',
        'Kathmandu, Nepal (KTM)',
        'Katowice, Poland (KTW)',
        'Kavala, Greece (KVA)',
        'Kayseri, Turkey (ASR)',
        'Kazan,, Russia (KZN)',
        'Kefallinia, Greece (EFL)',
        'Kerkyra, Greece (CFU)',
        'Khajuraho, India (HJR)',
        'Kharkov, Ukraine (HRK)',
        'Kiev, Ukraine - Zhulhany (IEV)',
        'Kiev, Ukraine - Borispol (KBP)',
        'Kigali, Rwanda (KGL)',
        'Kilimanjaro, Tanzania (JRO)',
        'Kingston, Jamaica - Norman Manley (KIN)',
        'Kingston, Jamaica - Tinson (KTP)',
        'Kinshasa, Congo (FIH)',
        'Kochi, Japan (KCZ)',
        'Koh Samui, Thailand (USM)',
        'Kolkata, India (CCU)',
        'Konya, Turkey (KYA)',
        'Kota Bharu, Malaysia (KBR)',
        'Kota Kinabalu, Malaysia (BKI)',
        'Kozhikode, India (CCJ)',
        'Krabi, Thailand (KBV)',
        'Krakow, Poland (KRK)',
        'Kuala Lumpur, Malaysia (KUL)',
        'Kuala Terengganu, Malaysia (TGG)',
        'Kuantan, Malaysia (KUA)',
        'Kuching, Malaysia (KCH)',
        'Kushiro, Japan (KUH)',
        'Kuusamo, Finland (KAO)',
        'Kuwait, Kuwait (KWI)',
        'Kwajalein, Marshall Islands (KWA)',
        'La Ceiba, Honduras (LCE)',
        'La Coruna, Spain (LCG)',
        'La Paz, Bolivia (LPB)',
        'La Paz, Mexico (LAP)',
        'La Rioja, Argentina (IRJ)',
        'La Romana, Dominican Republic (LRM)',
        'La Serena, Chile (LSC)',
        'Labuan, Malaysia (LBU)',
        'Lago Agrio, Ecuador (LGQ)',
        'Lagos, Nigeria (LOS)',
        'Lahadbatu, Malaysia (LDU)',
        'Lahore, Pakistan (LHE)',
        'Lamezia-Terme, Italy (SUF)',
        'Lampang, Thailand (LPI)',
        'Lampedusa, Italy (LMP)',
        'Lamu, Kenya (LAU)',
        'Langkawi, Malaysia (LGK)',
        'Lanzarote, Spain (ACE)',
        'Lanzhau, Guinea (LHW)',
        'Larnaca, Cyprus (LCA)',
        'Las Palmas, Spain (LPA)',
        'Launceston, TS, Australia (LST)',
        'Luanda, Angola (LAD)',
        'Leeds, United Kingdom (LBA)',
        'Legaspi, Philippines (LGP)',
        'Leh, India (IXL)',
        'Leipzig, Germany (LEJ)',
        'Lemnos, Greece (LXS)',
        'Leon, Mexico (BJX)',
        'Leticia, Colombia (LET)',
        'Lhasa, China (LXA)',
        'Liberia, Costa Rica (LIR)',
        'Libreville, Gabon (LBV)',
        'Liege, Belgium (LGG)',
        'Lille, France - Lesquin (LIL)',
        'Lilongwe, Malawi (LLW)',
        'Lima, Peru (LIM)',
        'Limbang, Malaysia (LMN)',
        'Limoges, France (LIG)',
        'Linkoping, Sweden (LPI)',
        'Linz, Austria (LNZ)',
        'Lisbon, Portugal (LIS)',
        'Liverpool, United Kingdom (LPL)',
        'Livingstone, Zambia (LVI)',
        'Ljubliana, Slovenia (LJU)',
        'Lome, Togo (LFW)',
        'London, United Kingdom - All airports (LON)',
        'London, United Kingdom - Gatwick (LGW)',
        'London, United Kingdom - Heathrow (LHR)',
        'London, United Kingdom - London City (LCY)',
        'London, United Kingdom - Luton (LTN)',
        'London, United Kingdom - Stansted (STN)',
        'Londonderry, United Kingdom (LDY)',
        'Londrina, PR, Brazil (LDB)',
        'Long Lellang, Malaysia (LGL)',
        'Loreto, Mexico (LTO)',
        'Lorient, France (LRT)',
        'Los Cabos, Mexico (SJD)',
        'Los Mochis, Mexico (LMM)',
        'Lourdes/Tarbes, France (LDE)',
        'Lozaro Cardenas, Mexico (LZC)',
        'Luanda, Angola (LAD)',
        'Lucknow, India (LKO)',
        'Luderitz, Namibia (LUD)',
        'Lugano, Switzerland (LUG)',
        'Lukla, Nepal (LUA)',
        'Lulea, Sweden (LLA)',
        'Lumbashi, Congo (FBM)',
        'Lusaka, Zambia (LUN)',
        'Luxembourg, Luxembourg (LUX)',
        'Luxor, Egypt (LXR)',
        'Lvov, Ukraine (LWO)',
        'Lyon, France - Satolas (LYS)',
        'Lyon, France - Lyon Part-Dieu Rail service (XYD)',
        'Maastricht, Netherlands (MST)',
        'Macapa, AP, Brazil (MCP)',
        'Macau, China (MFM)',
        'Maceio, AL, Brazil (MCZ)',
        'Mackay, QL, Australia (MKY)',
        'Madang, Papua New Guinea (MAG)',
        'Madinah, Saudi Arabia (MED)',
        'Madrid, Spain (MAD)',
        'Madurai, India (IXM)',
        'Mae Hong Son, Thailand (HGN)',
        'Mae Sot, Thailand (MAQ)',
        'Mahe Island, Seychelles (SEZ)',
        'Makhachkala, Russia (MCX)',
        'Malabo, Equatorial Guinea (SSG)',
        'Malaga, Spain (AGP)',
        'Malatya, Turkey (MLX)',
        'Male, Maldives (MLE)',
        'Malindi, Kenya (MYD)',
        'Malmo, Sweden (MMX)',
        'Malta, Malta (MLA)',
        'Manado, Indonesia (MDC)',
        'Managua, Nicaragua (MGA)',
        'Manaus, AM, Brazil (MAO)',
        'Manchester, United Kingdom (MAN)',
        'Mangalore, India (IXE)',
        'Manila, Philippines (MNL)',
        'Manizales, Colombia (MZL)',
        'Mannheim, Germany (MHG)',
        'Manzanillo, Mexico (ZLO)',
        'Manzini, Swaziland (MTS)',
        'Maputo, Mozambique (MPM)',
        'Mar Del Plata, BA, Argentina (MDQ)',
        'Maracaibo, Venezuela (MAR)',
        'Maracay, Venezuela (MYC)',
        'Margate, South Africa (MGH)',
        'Mariupol, Ukraine (MPW)',
        'Marseille, France (MRS)',
        'Marsh Harbour, Bahamas (MHH)',
        'Maseru, Lesotho (MSU)',
        'Mashad, Iran (MHD)',
        'Matamoros, Mexico (MAM)',
        'Mataram, Indonesia (AMI)',
        'Matsumoto, Japan (MMJ)',
        'Matsuyama, Japan (MYJ)',
        'Maun, Botswana (MUB)',
        'Mauritius, Mauritius (MRU)',
        'Mayaguez, Puerto Rico (MAZ)',
        'Mazatlan, Mexico (MZT)',
        'Medan, Indonesia (MES)',
        'Medellin, Colombia - Jose Marie Cordova (MDE)',
        'Meixian, China (MXZ)',
        'Melbourne, Victoria, Australia (MEL)',
        'Memanbetsu, Japan (MMB)',
        'Mendoza, MD, Argentina (MDZ)',
        'Menorca, Spain (MAH)',
        'Merdey, Indonesia (RDE)',
        'Merida, Mexico (MID)',
        'Mexicali, Mexico (MXL)',
        'Mexico City, Mexico (MEX)',
        'Mikonos, Greece (JMK)',
        'Milan, Italy - Orio Al Serio (BGY)',
        'Milan, Italy - Linate (LIN)',
        'Milan, Italy - Malpensa (MXP)',
        'Minatitla, Mexico (MTT)',
        'Mineralnye Vody, Russia (MRV)',
        'Minsk, Belarus - Minsk International 1 (MHP)',
        'Minsk, Belarus - Minsk International 2 (MSQ)',
        'Miri, Malaysia (MYY)',
        'Mogadishu, Somalia (MGQ)',
        'Mokpo, South Korea (MPK)',
        'Molde, Norway (MOL)',
        'Mombasa, Kenya (MBA)',
        'Monastir, Tunisia (MIR)',
        'Monrovia, Liberia (ROB)',
        'Montego Bay, Jamaica (MBJ)',
        'Monteria, Colombia (MTR)',
        'Monterrey, Mexico (MTY)',
        'Montevideo, Uruguay (MVD)',
        'Montpellier, France (MPL)',
        'Montserrat, Montserrat (MNI)',
        'Mora, Sweden (MXX)',
        'Moranbah, QL, Australia (MOV)',
        'Morelia, Mexico (MLM)',
        'Morioka, Japan (HNA)',
        'Moroni, Comoros (HAH)',
        'Moscow, Russia - all locations (MOW)',
        'Moscow, Russia - Domodedovo (DME)',
        'Moscow, Russia - Sheremetyevo (SVO)',
        'Moscow, Russia - Vnukovo (VKO)',
        'Mostar, Bosnia and Herzegovina (OMO)',
        'Mount Cook, New Zealand (MON)',
        'Mount Hagen, Papua New Guinea (HGU)',
        'Mtwara, Tanzania (MYW)',
        'Mudanjiang, China (MDG)',
        'Muenster, Germany (FMO)',
        'Mulhouse, France (MLH)',
        'Mulu, Malaysia (MZV)',
        'Mumbai, India (BOM)',
        'Munich, Germany (MUC)',
        'Murcia, Spain (MJV)',
        'Murmansk, Russia (MMK)',
        'Mus, Turkey (MSR)',
        'Muscat, Oman (MCT)',
        'Mwanza, Tanzania (MWZ)',
        'Mytilene, Greece (MJT)',
        'Nadi, Fiji (NAN)',
        'Nagasaki, Japan (NGS)',
        'Nagoya, Japan (NGO)',
        'Nagpur, India (NAG)',
        'Nairobi, Kenya - Jomo Kenyatta Intl (NBO)',
        'Nairobi, Kenya - Wilson (WIL)',
        'Nakhon Ratchosima, Thailand (NAK)',
        'Nakhon Si Thammarat, Thailand (NST)',
        'Nampula, Mozambique (APL)',
        'Nan, Thailand (NNT)',
        'Nanking/Nanjing, China (NKG)',
        'Nanning, China (NNG)',
        'Nantes, France - Nantes Atlantique (NTE)',
        'Nantes, France - Rail service (QJZ)',
        'Nantong, China (NTG)',
        'Napier-Hastings, New Zealand (NPE)',
        'Naples, Italy (NAP)',
        'Narathiwat, Thailand (NAW)',
        'Nassau, Bahamas - International (NAS)',
        'Nassau, Bahamas - Paradise Island (PID)',
        'Natal, RN, Brazil (NAT)',
        'Navegantes, SC, Brazil (NVT)',
        'Ndola, Zambia (NLA)',
        'Neiva, Colombia (NVA)',
        'Nelso, New Zealand (NSN)',
        'Nelspruit, South Africa (NLP)',
        'Neuquen, NE, Argentina (NQN)',
        'Nevis, St. Kitts and Nevis (NEV)',
        'New London/Groton (GON)',
        'New Plymouth, New Zealand (NPL)',
        'Newcastle, New South Wales, Australia - Belmont (BEO)',
        'Newcastle, New South Wales, Australia (NTL)',
        'Newcastle, United Kingdom (NCL)',
        'Newquay, United Kingdom (NQY)',
        'Niamey, Niger (NIM)',
        'Nice, France (NCE)',
        'Nimes, France (FNI)',
        'Ningbo, China (NGB)',
        'Niuatoputapu, Tonga (NTT)',
        'Nizhniy Novgorod, Russia (GOJ)',
        'Ndjamena, Chad (NDJ)',
        'Norrkoping, Sweden (NRK)',
        'North Eleuthera, Bahamas (ELH)',
        'Norwich, United Kingdom (NWI)',
        'Nottingham, United Kingdom (EMA)',
        'Nouadhiba, Mauritania (NDB)',
        'Nouakchott, Mauritania (NKC)',
        'Noumea, New Caledonia - Tontouta (NOU)',
        'Noumea, New Caledonia - Magenta (GEA)',
        'Novosibirsk, Russia - Tolmachevo (OVB)',
        'Nuevo Laredo, Mexico (NLD)',
        'Nuku\'Alofa, Tonga (TBU)',
        'Nuremberg, Germany - Rail service (ZAQ)',
        'Nuremberg, Germany (NUE)',
        'Oaxaca, Mexico (OAX)',
        'Obihiro, Japan (OBO)',
        'Ocho Rios, Jamaica (OCJ)',
        'Odessa, Ukraine (ODS)',
        'Ohrid, Macedonia (OHD)',
        'Oita, Japan (OIT)',
        'Okayama, Japan (OKJ)',
        'Okinawa, Japan (OKA)',
        'Olbia, Italy (OLB)',
        'Omsk, Russia (OMS)',
        'Oradea, Romania (OMR)',
        'Oran, Algeria (ORN)',
        'Orange, New South Wales, Australia (OAG)',
        'Orebro, Sweeden - Obrebro-Bofors (ORB)',
        'Ornskoldsvik, Sweden (OER)',
        'Osaka, Japan - all airports (OSA)',
        'Osaka, Japan - Itami (ITM)',
        'Osaka, Japan - Kansai Intl (KIX)',
        'Oskarshamn, Sweden (OSK)',
        'Oslo, Norway (OSL)',
        'Oslo, Norway - Sandefjord (TRF)',
        'Ostersund, Sweden (OSD)',
        'Ostrava, Czech Republic (OSR)',
        'Ouagadougou, Burkina Faso (OUA)',
        'Ouarzazate, Morocco (OZZ)',
        'Oujda, Morocco (OUD)',
        'Oulu, Finland (OUL)',
        'Padang, Indonesia (PDG)',
        'Paderborn, Germany (PAD)',
        'Palanga, Lithuania (PLQ)',
        'Palembang, Indonesia (PLM)',
        'Palermo, Sicily, Italy (PMO)',
        'Palma Mallorca, Spain and Canary Islands (PMI)',
        'Palmerston North, New Zealand (PMR)',
        'Pamplona, Spain (PNA)',
        'Panama City, Panama - Tocumen Intl (PTY)',
        'Panama City, Panama - Paitilla (PAC)',
        'Pantelleria, Italy (PNL)',
        'Papeete, French Polynesia (PPT)',
        'Paphos, Cyprus (PFO)',
        'Paradise Island, Bahamas (PID)',
        'Paramaribo, Suriname - Zanderij Intl (PBM)',
        'Paramaribo, Suriname - Zorg En Hoop (ORG)',
        'Paris, France - All airports (PAR)',
        'Paris, France - Charles Degaulle (CDG)',
        'Paris, France - Orly (ORY)',
        'Pasto, Colombia (PSO)',
        'Patna, India (PAT)',
        'Pau, France (PUF)',
        'Pekanbaru, Indonesia (PKU)',
        'Penang, Malaysia (PEN)',
        'Pereira, Colombia (PEI)',
        'Perigueux, France (PGX)',
        'Perm, Russia (PEE)',
        'Perpignan, France (PGF)',
        'Perth, Western Australia, Australia (PER)',
        'Perugia, Italy (PEG)',
        'Pescara, Italy (PSR)',
        'Peshawar, Pakistan (PEW)',
        'Petrozavodsk, Russia (PES)',
        'Phalaborwa, South Africa (PHW)',
        'Phitsanulok, Thailand (PHS)',
        'Phnom Penh, Cambodia (PNH)',
        'Phrae, Thailand (PRH)',
        'Phuket, Thailand (HKT)',
        'Piedras Negras, Mexico (PDS)',
        'Pietermaritzburg, South Africa (PZB)',
        'Pietersburb, South Africa (PTG)',
        'Pisa, Italy - Gal Galilei (PSA)',
        'Piura, Peru (PIU)',
        'Plettenburg Bay, South Africa (PBZ)',
        'Podgoriea, Serbia and Montenegro - Golubovci (TGD)',
        'Pohnpei, Micronesia (PNI)',
        'Pointe Noire, Congo (PNR)',
        'Pointe-a-Pitre, Guadeloupe (PTP)',
        'Poitiers, France - Biard (PIS)',
        'Pokhara, Nepal (PKR)',
        'Ponce, Puerto Rico (PSE)',
        'Ponta Delgada, Portugal (PDL)',
        'Pontianak, Indonesia (PNK)',
        'Porbandar, India (PBD)',
        'Porlamar, Venezuela (PMV)',
        'Port Au Prince, Haiti (PAP)',
        'Port Elizabeth, South Africa (PLZ)',
        'Port Gentil, Gabon (POG)',
        'Port Harcourt, Nigeria (PHC)',
        'Port Headland, WA, Australia (PHE)',
        'Port Moresby, Papua New Guinea (POM)',
        'Port of Spain, Trinidad (POS)',
        'Port Sudan, Sudan (PZU)',
        'Porto Alegre, RS, Brazil (POA)',
        'Porto Santo, Portugal (PXO)',
        'Porto Seguro, Brazil (BPS)',
        'Porto Velho, RO, Brazil (PVH)',
        'Porto, Portugal (OPO)',
        'Posadas, MI, Argentina (PSS)',
        'Poza Rico, Mexico (PAZ)',
        'Poznan, Poland (POZ)',
        'Prague, Czech Republic (PRG)',
        'Praia, Cape Verde (RAI)',
        'Presidente Prudente, SP, Brazil (PPB)',
        'Preveza/Lefkas, Greece (PVK)',
        'Pristina, Serbia and Montenegro (PRN)',
        'Providenciales, Turks and Caicos Islands (PLS)',
        'Puebla, Mexico (PBC)',
        'Puerto del Rosario, Spain (FUE)',
        'Puerto Escondido, Mexico (PXM)',
        'Puerto Maldonado, Peru (PEM)',
        'Puerto Montt, Chile (PMC)',
        'Puerto Plata, Dominican Republic (POP)',
        'Puerto Princesa, Philippines (PPS)',
        'Puerto Vallarta, Mexico (PVR)',
        'Pula, Croatia (PUY)',
        'Pune, India (PNQ)',
        'Punta Arenas, Chile (PUQ)',
        'Punta Cana, Dominican Republic (PUJ)',
        'Pyongyang, North Korea (FNJ)',
        'Qingdao, China (TAO)',
        'Queenstown, New Zealand (ZQN)',
        'Queretaro, Mexico (QRO)',
        'Quetta, Pakistan (UET)',
        'Quimper, France (UIP)',
        'Quito, Ecuador (UIO)',
        'Rabat, Morocco (RBA)',
        'Rabaul, Papua New Guinea (RAB)',
        'Rajkot, India (RAJ)',
        'Ranchi, India (IXR)',
        'Rarotonga, Cook Islands (RAR)',
        'Ras Al Khaimah, United Arab Emirates (RKT)',
        'Rasht, Iran (RAS)',
        'Recife, PE, Brazil (REC)',
        'Reggio Calabria, Italy (REG)',
        'Rennes, France (RNS)',
        'Resistencia, CW, Argentina (RES)',
        'Reykjavik, Iceland (KEF)',
        'Reynossa, Mexico (REX)',
        'Rhodes, Gabon (RHO)',
        'Riberalta, Bolivia (RIB)',
        'Richards Bay, South Africa (RCB)',
        'Riga, Latvia (RIX)',
        'Rimini, Italy (RMI)',
        'Rio Branco, AC, Brazil (RBR)',
        'Rio De Janeiro, RJ, Brazil (GIG)',
        'Rio Gallegos, Argentina - Internacional (RGL)',
        'Rio Grande, TF, Argentina (RGA)',
        'Riohacha, Colombia (RCH)',
        'Riyadh, Saudi Arabia (RUH)',
        'Roatan, Honduras (RTB)',
        'Rodez, France (RDZ)',
        'Rome, Italy - All airports (ROM)',
        'Rome, Italy - Ciampino (CIA)',
        'Rome, Italy - Leonardo Da Vinci/Fiumicino (FCO)',
        'Ronneby, Sweden (RNB)',
        'Roros, Norway (RRS)',
        'Rosario, SF, Argentina (ROS)',
        'Rostock-Laage, Germany (RLG)',
        'Rostov, Russia (ROV)',
        'Rotorua, New Zealand (ROT)',
        'Rotterdam, Netherlands (RTM)',
        'Rovaniemi, Finland (RVN)',
        'Saint Croix, U.S. Virgin Islands (STX)',
        'Saint Lucia, ST. LUCIA (SLU)',
        'Saint Maarten, Netherlands Antilles (SXM)',
        'Saint Petersburg, Russia - Pulkovo (LED)',
        'Saint Thomas, U.S. Virgin Islands (STT)',
        'Saipan, Northern Mariana Islands (SPN)',
        'Sakon Nakhon, Thailand (SNO)',
        'Saltillo, Mexico (SLW)',
        'Salvadore, BA, Brazil (SSA)',
        'Salzburg, Austria (SZG)',
        'Samara, Russia (KUF)',
        'Samos, Greece (SMI)',
        'San Andres Island, Colombia (ADZ)',
        'San Carlos, Argentina (BRC)',
        'San Jose, Costa Rica - Juan Santa Maria (SJO)',
        'San Juan, Puerto Rico (SJU)',
        'San Juan, SJ, Argentina (UAQ)',
        'San Luis Potosi, Mexico (SLP)',
        'San Pedro Sula, Honduras (SAP)',
        'San Salvador, El Salvador (SAL)',
        'Sana\'a, Yemen (SAH)',
        'Santa Cruz De La Palma, Spain and Canary Islands - La Palma (SPC)',
        'Santa Cruz, Bolivia (VVI)',
        'Santa Maria, Brazil (RIA)',
        'Santa Marta, Colombia (SMR)',
        'Santa Rosa, LP, Argentina (RSA)',
        'Santarem, PA, Brazil (STM)',
        'Santiago, Chile (SCL)',
        'Santiago, Dominican Republic (STI)',
        'Santo Domingo, Dominican Republic - Herrera (HEX)',
        'Santo Domingo, Dominican Republic - Las Americas (SDQ)',
        'Sanya, China (SYX)',
        'Sao Paulo, Brazil - Congonhas (CGH)',
        'Sao Paulo, Brazil - Viracopos (VCP)',
        'Sao Paulo, Brazil - Guarulhos Intl (GRU)',
        'Sao Tome Is., Sao Tome and Principe (TMS)',
        'Sapporo, Japan - Chitose (CTS)',
        'Sapporo, Japan - Okadama (OKD)',
        'Sau Luiz, MA, Brazil (SLZ)',
        'Semarang, Indonesia (SRG)',
        'Seoul, South Korea - All Airports (SEL)',
        'Seoul, South Korea - Incheon International (ICN)',
        'Sevilla, Spain and Canary Islands (SVQ)',
        'Shanghai, China (PVG)',
        'Shannon, Ireland (SNN)',
        'Shantou, China (SWA)',
        'Sharm El Sheikh, Egypt (SSH)',
        'Sheffield, United Kingdom (SZD)',
        'Shenzhen, China (SZX)',
        'Shetland Islands, United Kingdom - Sumburgh (LSI)',
        'Shiraz, Iran (SYZ)',
        'Siem Reap, Cambodia (REP)',
        'Singapore, Singapore - Changi (SIN)',
        'Singapore, Singapore - Seletar (XSP)',
        'Sivas, Turkey (VAS)',
        'Skiathos, Greece (JSI)',
        'Skukuza, South Africa (SZK)',
        'Sligo, Ireland (SXL)',
        'Sofia, Bulgaria (SOF)',
        'Solo City, Indonesia (SOC)',
        'South Hampton, United Kingdom (SOU)',
        'Split, Croatia (SPU)',
        'Srinagar, India (SXR)',
        'St. Croix Island, U.S. Virgin Islands (STX)',
        'St Denis de la Reunion, Reunion (RUN)',
        'St Kitts, St Kitts and Nevis (SKB)',
        'St Vincent, Saint Vincent and the Grenadines (SVD)',
        'St. Etienne, France (EBU)',
        'St. Eustatius, Netherlands Antilles (EUX)',
        'St. Lucia, St. Lucia - Hawnorra (UVF)',
        'St. Lucia, St. Lucia (UVF)',
        'St. Petersburg, Russia (LED)',
        'St. Thomas Island, U.S. Virgin Islands (STT)',
        'Stavanger, Norway (SVG)',
        'Stockholm, Sweden - All airports (STO)',
        'Stockholm, Sweden - Arlanda (ARN)',
        'Stockholm, Sweden - Bromma (BMA)',
        'Stornoway, United Kingdom (SYY)',
        'Strasbourg, France - Entzheim (SXB)',
        'Stuttgart, Germany - Echterdingen (STR)',
        'Stuttgart, Germany - Rail service (ZWS)',
        'Sun City, South Africa (NTY)',
        'Surabaya, Indonesia (SUB)',
        'Surat Thani, Thailand (URT)',
        'Sydney, New South Wales, Australia (SYD)',
        'Sylhet, Bangladesh (ZYL)',
        'Szczecin, Poland (SZZ)',
        'Tabarka, Tunisia (TBJ)',
        'Tabatinga, AM, Brazil (TBT)',
        'Tacloban, Philippines (TAC)',
        'Tacna, Peru (TCQ)',
        'Taipei, Taiwan - Sung Shan (TSA)',
        'Taipei, Taiwan - Chiang Kai Shek (TPE)',
        'Tallinn, Estonia (TLL)',
        'Tampere, Finland (TMP)',
        'Tampico, Mexico (TAM)',
        'Tangier, Morocco (TNG)',
        'Tanjung Pandan, Indonesia (TJQ)',
        'Tanjung Selor, Indonesia (TJS)',
        'Tapachula, Mexico (TAP)',
        'Tarakan, Indonesia (TRK)',
        'Tarapoto, Peru (TPP)',
        'Tari, Papua New Guinea (TIZ)',
        'Tashkent, Uzbekistan (TAS)',
        'Taupo, New Zealand (TUO)',
        'Tauranga, New Zealand (TRG)',
        'Tawau, Malaysia (TWU)',
        'Tbilisi, Georgia (TBS)',
        'Teesside, United Kingdom (MME)',
        'Tegucigalpa, Honduras (TGU)',
        'Tehran, Iran - Mehrabad (THR)',
        'Tel Aviv, Israel (TLV)',
        'Temuco, Chile (ZCO)',
        'Tenerife, Spain and Canary Islands - Norte Los Rodeos (TFN)',
        'Tenerife, Spain and the Canary Islands - Sur Reina Sofia (TFS)',
        'Tepic, Mexico (TPQ)',
        'Terceira Island, Portugal (TER)',
        'Teresina, PI, Brazil (THE)',
        'Tete, Mozambique (TET)',
        'Tetuan, Morocco (TTU)',
        'Thessaloniki, Greece (SKG)',
        'Thira, Greece (JTR)',
        'Thiruvananthapuram, India (TRV)',
        'Tianjn, China (TSN)',
        'Tijuana, Mexico (TIJ)',
        'Timaru, New Zealand (TIU)',
        'Timosoara, Romania (TSR)',
        'Tioman, Malaysia (TOD)',
        'Tirana, Albania (TIA)',
        'Tiree, United Kingdom (TRE)',
        'Tiruchirapally, India (TRZ)',
        'Tobago, Trinidad and Tobago (TAB)',
        'Tokushima, Japan (TKS)',
        'Tokyo, Japan - All airports (TYO)',
        'Tokyo, Japan - Haneda (HND)',
        'Tokyo, Japan - Narita (NRT)',
        'Toluco, Mexico (TLC)',
        'Torreon, Mexico (TRC)',
        'Tortola, British Virgin Islands (TOV)',
        'Toulon, France (TLN)',
        'Toulouse, France (TLS)',
        'Tours, France (TUF)',
        'Townsville, QL, Australia (TSV)',
        'Toyama, Japan (TOY)',
        'Trabzon, Turkey (TZX)',
        'Trang, Thailand (TST)',
        'Trapani, Italy (TPS)',
        'Treasure Cay, Bahamas (TCB)',
        'Trelew, CB, Argentina (REL)',
        'Trieste, Italy (TRS)',
        'Trinidad, Trinidad and Tobago (POS)',
        'Tripoli, Latvia (TIP)',
        'Trollhattan, Sweden (THN)',
        'Tromso, Norway (TOS)',
        'Trondheim, Norway (TRD)',
        'Trujillo, Peru (TRU)',
        'Truk, Micronesia (TKK)',
        'Tucuman, TU, Argentina (TUC)',
        'Tunis, Tunisia (TUN)',
        'Turin, Italy (TRN)',
        'Turku, Finland (TKU)',
        'Tuxtla Gutierrez, Mexico (TGZ)',
        'Ubon Ratchathani, Thailand (UBP)',
        'Udaipur, Indonesia (UDR)',
        'Udon Thani, Thailand (UTH)',
        'Ufa, Russia (UFA)',
        'Ujung Pandang, Indonesia (UPG)',
        'Ulaanbaatar, Mongolia (ULN)',
        'Ulsan, South Korea (USN)',
        'Umea, Sweden (UME)',
        'Umtata, South Africa (UTT)',
        'Upington, South Africa (UTN)',
        'Uruapan, Mexico (UPN)',
        'Urumqi, China (URC)',
        'Ushuaia, TF, Argentina (USH)',
        'Utapao, Thailand (UTP)',
        'Vaasa, Finland (VAA)',
        'Vadodara, India (BDQ)',
        'Valdivia, Chile (ZAL)',
        'Valencia, Spain (VLC)',
        'Valledupar, Colombia (VUP)',
        'Van, Turkey (VAN)',
        'Vancouver, BC (YVR)',
        'Varanasi, India (VNS)',
        'Varna, Bulgaria (VAR)',
        'Vava\'u, Tonga (VAV)',
        'Vaxjo, Sweden (VXO)',
        'V.C. Bird International, Antigua & Barbuda (ANU)',
        'Venice, Italy - Marco Polo (VCE)',
        'Venice, Italy - Treviso (TSF)',
        'Veracruz, Mexico (VER)',
        'Varadero, Cuba (VRA)',
        'Verona, Italy (VRN)',
        'Victoria Falls, Zimbabwe (VFA)',
        'Vienna, Austria (VIE)',
        'Vientiane, Laos - Wattay (VTE)',
        'Vigo, Spain (VGO)',
        'Villahermosa, Mexico (VSA)',
        'Vilnius, Lithuania (VNO)',
        'Visby, Sweden (VBY)',
        'Vladivostok, Russia (VVO)',
        'Walvis Bay, Namibia (WVB)',
        'Wanaka, New Zealand (WKA)',
        'Wanganui, New Zealand (WAG)',
        'Warsaw, Poland (WAW)',
        'Wellington, New Zealand (WLG)',
        'Wenzhou, China (WNZ)',
        'Westerland, Germany (GWT)',
        'Westport, New Zealand (WSZ)',
        'Wewak, Papua New Guinea (WWK)',
        'Whakatane, New Zealand (WHK)',
        'Whangarei, New Zealand (WRE)',
        'Wick, United Kingdom (WIC)',
        'Wroclaw, Poland (WRO)',
        'Wuhan, China (WUH)',
        'Xiamen, China (XMN)',
        'Xi An, China - Xianyang (XIY)',
        'Yamagata, Japan (GAJ)',
        'Yangon, Myanmar (RGN)',
        'Yantai, China (YNT)',
        'Yaounde, Cameroon (YAO)',
        'Yazd, Iran (AZD)',
        'Yeosu, South Korea (RSU)',
        'Yerevan, Armenia (EVN)',
        'Yichang, China (YIH)',
        'Yinchuan, China (INC)',
        'Yogyakarta, Indonesia (JOG)',
        'Zadar, Croatia (ZAD)',
        'Zagreb, Croatia (ZAG)',
        'Zakinthos Island, Greece (ZTH)',
        'Zamboanga, Philippines (ZAM)',
        'Zanzibar, Tanzania - Kisauni (ZNZ)',
        'Zaragoza, Spain and Canary Islands (ZAZ)',
        'Zhanjiang, China (ZHA)',
        'Zhengzha, China (CGO)',
        'Zihuatanejo/Ixtapa, Mexico (ZIH)',
        'Zurich, Switzerland (ZRH)']
}
